apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scarab-results
  namespace: ucsc-hsc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
